---
- name: Setup vprofile stack
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import vpc setup variable
      include_vars: vars/output_vars
    
    - name: import vprofile setup variable
      include_vars: vars/vpro-stack-setup

    - name: create key pair
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: save private key
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed