---
- name: Setup vprofile stack
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import vpc setup variable
      include_vars: vars/output_vars
    
    - name: import vprofile setup variable
      include_vars: vars/vpro-stack-setup

    - name: create key pair
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: save private key
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed

    - name: sg for LB
      ec2_group:
        name: vproELB-sg
        description: allow port 80 frorm everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules: 
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELBSG_out

    - name: sg for vprofile stack
      ec2_group:
        name: vprostack-sg
        description: allow port 22 
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{vproELBSG_out.group_id}}"

          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{bastionSGid}}"
      register: vprostackSG_out

    - name: sg for vprofile stack allow within itself
      ec2_group:
        name: vprostack-sg
        description: allow port 22  for
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{vprostackSG_out.group_id}}"